# Makefile para o compilador LPDC
# Projeto 2 de Compiladores

CC = gcc
CFLAGS = -Wall -Wextra -std=c99

# Arquivos fonte que você implementou
SRC = main.c asdr.c tabsimb.c gerador.c

# Arquivos objeto fornecidos pelo professor
OBJ = analex.o hash.o

# Nome do executável
BIN = lpdc

# Regra principal
all: $(BIN)

# Compilação do executável
$(BIN): $(SRC) $(OBJ)
	$(CC) $(CFLAGS) -o $(BIN) $(SRC) $(OBJ)

# Limpeza
clean:
	rm -f $(BIN) *.mepa *.ts

# Limpeza completa (incluindo arquivos de saída dos testes)
cleanall: clean
	rm -f *.mepa *.ts

# Regra para testar com um arquivo específico
test: $(BIN)
	./$(BIN) teste.lpd

.PHONY: all clean cleanall test
